name: Update HTML with Dynamic Nonce

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes, adjust as needed.
  push:
    branches:
      - main

jobs:
  update-html:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Clean previous installations
      run: rm -rf node_modules package-lock.json
    
    - name: Install dependencies
      run: npm install

    - name: Run script to update HTML
      run: node sc.js

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        # Stage all modified files
        git add .
        
        # Commit changes
        git commit -m "Update index.html with dynamic nonce" || echo "No changes to commit"
        
        # Pull remote changes to avoid conflicts
        git pull --rebase origin main
        
        # Push changes to the remote repository
        git push
